### ISSUE TITLE
[BUG] xs font size not exported correctly

### ISSUE THREAD

**Issue by ErikFontanel** [jan-dh/figma-tailwindcss#24] opened 2021-05-27 12:23 UTC
### Description
The export preview of font sizes looks like this:
![image](https://user-images.githubusercontent.com/917819/119824820-98387080-bef6-11eb-805e-53f9ae0c1bd1.png)

With `2xs` and `xs` being huge. And the corresponding json that is generated:
```json
 "fontSize": {
  "2xs": "0.75rem",
  "xs": "8rem",
  "sm": "0.875rem",
  "base": "1rem",
  "lg": "1.125rem",
  "xl": "1.25rem",
  "2xl": "1.5rem",
  "3xl": "1.875rem",
  "4xl": "2.25rem",
  "5xl": "3rem",
  "6xl": "3.75rem",
  "7xl": "4.5rem",
  "8xl": "6rem"
 },
```

Despite the preview being wrong, the json for `2xs` is correct. But note the wrong font size for xs,  it's missing `0.`. 

### Steps to reproduce
1. Launch the plugin
2. Choose a base font size 

### Additional info
- Figma version: Figma Desktop App version 98.13
- OS version: 10.13.6

**Comment by jan-dh** [comment] 2021-05-27 13:59
@ErikFontanel would it be possible to share your Figma file? Can't reproduce this

**Comment by ErikFontanel** [comment] 2021-06-09 13:14
I've created a [reduced test case](https://www.figma.com/file/Rxn1Qoc6ja3wBuy0Vlp2ma/TailwindCSS-plugin-font-sizes-test-case?node-id=0%3A1). It's an empty file except I copied over all the text styles from the file that caused this and I'm able to reproduce the issue.

**Comment by jan-dh** [comment] 2021-06-10 13:53
Fixed in latest release

**Closed by jan-dh** 2021-06-10 13:53 UTC
Labels: bug
